### PR TITLE
Ignore Strong references

### PR DESCRIPTION
**Pull request by chrisvire**

### CODE REVIEW

**Comment by chrisvire** [comment]
I need to handle when strongs references are in `\wj`:

> \v 3  \wj “\+w Blessed|strong="G3107"\+w* \+w are|strong="G1510"\+w* \+w the|strong="G3588"\+w* \+w poor|strong="G4434"\+w* \+w in|strong="G4434"\+w* \+w spirit|strong="G4151"\+w*,\wj* 
\q2 \wj  \+w for|strong="G3754"\+w* \+w theirs|strong="G0846"\+w* \+w is|strong="G1510"\+w* \+w the|strong="G3588"\+w* \+w Kingdom|strong="G0932"\+w* \+w of|strong="G0932"\+w* \+w Heaven|strong="G3772"\+w*.\wj*\x + \xo 5:3  \xt Isaiah 57:15; 66:2\x*

**Comment by chrisvire** [comment]
@davidmoore1 I am asking on Proskomma Discord server if there is a better way to mutate the Proskomma data with GraphQL instead of filtering the text on the way in.

**Comment by chrisvire** [comment]
FYI: size difference

before: 8.1MB
after: 3.4MB

**Review by davidmoore1 — APPROVED** [review]
LGTM

**Pull request merged**
