### PR TITLE
Feature: Reference Parsing

### PR DESCRIPTION
**Pull request by jakedcolbert**
Implements #388
* Develop utilities for parsing in-text references and generating
  respective HTML content.
* Develop tests to evaluate effectiveness of developed functions
* Develop footnote content display component with stack functionality.

### CODE REVIEW

**Comment by chrisvire** [comment]
@jakedcolbert I am going through PRs and noticed this one. Do you believe this is ready?

**Comment by jakedcolbert** [comment]
@chrisvire Yes, it meets the requirements of #388

**Comment by chrisvire** [comment]
@jakedcolbert I am confused on what I should be looking for?  Is there specific Langauage/Book/Chapter/Verse where I can see this in action?

**Review by chrisvire — APPROVED** [review]
👍

**Pull request merged**
