### PR TITLE
Dynamic Dropdown Labels

### PR DESCRIPTION
**Pull request by jakedcolbert**
Implements [#58](https://github.com/gordon-cs/appbuilder-pwa/issues/58)

### CODE REVIEW

**Comment by jakedcolbert** [comment]
Requires review: 

Encountered an issue where on:outclick rewrites the store values to empty strings which halts navigation when a verse is chosen. It was intended to clear the values of the nextRef stores so that the dropdown labels would revert to the current state of the ref. 

The following lines of code were removed to resolve this issue: 

BookSelector.svelte line 98 and ChapterSelector.svelte line 70:

```html
                    on:outclick={() => {
                        chapterSelector.setActive(c);
                        $nextRef = {book: book, chapter: chapter}
                    }}
```

**Comment by jakedcolbert** [comment]
Trying to identify what lint is having a problem with ...

**Comment by chrisvire** [comment]
> Trying to identify what lint is having a problem with ...

It is something with the outclick code which needs to be removed anyway.  If I remove it, I don't get the lint warning.

**Review by chrisvire — APPROVED** [review]
LGTM

**Pull request merged**
