### PR TITLE
Dropdown Restyling

### PR DESCRIPTION
**Pull request by jakedcolbert**

### CODE REVIEW

**Comment by jakedcolbert** [comment]
Deleting the file is not the same as untracking any changes made to it. How do I fix this?

**Comment by jakedcolbert** [comment]
To Do: 

- Grid List items not dynamically colored
- Dropdown dismisses on tab change

**Comment by jakedcolbert** [comment]
Book Abbreviations? See line 73 of BookSelector.svelte

**Comment by jakedcolbert** [comment]
fix strange wrapping with items less than cols width

**Comment by jakedcolbert** [comment]
Book Collection does not navigate reference correctly when dealing with nextRef.chapter. I think its being overridden by Chapter Collector? Is there a way to implement mutexs for stores?

**Comment by chrisvire** [comment]
@jakedcolbert I have added `$refs.collection` property so that you don't have to do `const colId = $refs.docSet.split('_')[1];` but just use `$refs.collection` instead.

Update main in your fork and then rebase your branch off of main.  If you need help doing this, let me know.

**Comment by chrisvire** [comment]
Latest status that I know of:

> chrisvire — 01/23/2023 4:34 PM
How is your PR.  Is it ready to be reviewed?
Jake Colbert (Gordon) — 01/23/2023 6:00 PM
It should be all set besides one error. In the latest commit, book selector dropdown doesn’t navigate to the chosen chapter correctly.

**Comment by jakedcolbert** [comment]
Great. Will make those changes today. I have not solved the problem yet but will devote today to finding a solution. The PR will be ready for review by tomorrow.

**Comment by chrisvire** [comment]
The styling looks good.  I said to work on the updating of the book name and chapter into a separate PR.  Currently the book name doesn't change at all.  I am going to accept this PR with the expectation that you will be able to get the book name and chapter updated fairly soon.

**Review by chrisvire — APPROVED** [review]

**Pull request merged**
