### PR TITLE
SideBySide Menu

### PR DESCRIPTION
**Pull request by jakedcolbert**
Implementation of the Book Collection Selector menu SideBySide feature.

### CODE REVIEW

**Comment by jakedcolbert** [comment]
if an option is selected on one tab but that tab is then switched, it should abandon the previous setting. Currently not implemented

**Comment by jakedcolbert** [comment]
Requires theming support. It may be using some wrong themes and can appear wrong in dark mode.

**Comment by jakedcolbert** [comment]
SideBySide menu is completed and is ready for your review. I will open a separate PR for VerseByVerse

**Comment by jakedcolbert** [comment]
Still to do: 
- [] Theming Support
- [] Implementation of a general purpose navigation function compared to the seperate handleClick. Will be especially useful with VerseByVerse implementation

**Comment by chrisvire** [comment]
It looks like you still have things to do. I am removing myself as reviewer.  Please add me when it is ready for review

**Comment by jakedcolbert** [comment]
Ready for review. Some under the hood functionality needs to still be implemented but will be fixed in the VerseByVerse PR

**Comment by jakedcolbert** [comment]
Latest dependency commit changed appearance of some components. Disregard this PR, see newest changes and implementation of VerseByVerse in #256

**Pull request closed without merging**
