### PR TITLE
#284 hover bugfix

### PR DESCRIPTION
**Pull request by jakedcolbert**

### CODE REVIEW

**Comment by jakedcolbert** [comment]
Needs a fix actually, navigates to what was first selected

**Comment by jakedcolbert** [comment]
Look into touchend registering when trying to scroll

**Comment by chrisvire** [comment]
@jakedcolbert I can't remember what this was supposed to fix (no description provided).  Can you remember or close?

**Comment by jakedcolbert** [comment]
@chrisvire fixes #284

**Pull request closed without merging**
