### PR TITLE
Enable text selection toolbar play button functionality

### LINKED ISSUE #362: Audio: enable the play button in the text selection toolbar to trigger the audio to play from the verse selected
* If the file has timing information the play button when pressed should cause the text selection toolbar to disappear and the audio bar to reappear. 
* The audio should start playing from the start of the verse selected.
* If the file does not have timing information the audio play buttons should not be displayed.

### PR DESCRIPTION
**Pull request by ChristopherRankin**
* The play button plays the audio if verses are selected and audio paused.
* The play and repeat buttons disappear if there are no timing files.
* The audio starts from the verse that is selected closest to the beginning of the chapter.
* If audio is playing, verse selection is disabled.
* Fixes #362.

### CODE REVIEW

**Comment by chrisvire** [comment]
@ChristopherRankin:
I was on Matthew 1. 
I selected v18 "Now the birth of Jesus Chris was like this"
I clicked on the play button in the text selection toolbar
It started play from Matt 1:1

**Comment by chrisvire** [comment]
@ChristopherRankin You should also turn on the AudioBar ($audioActive = true) when you start playing.

**Comment by ChristopherRankin** [comment]
The errors should be fixed now.

**Review by chrisvire — CHANGES_REQUESTED** [review]
When playing from the TextSelectionToolbar, it should start playing from the selected verse.

**Comment by ChristopherRankin** [comment]
Changes have been made.

**Review by chrisvire — APPROVED** [review]
👍

**Pull request merged**
