### PR TITLE
#289 Implement viewer

### PR DESCRIPTION
**Pull request by jakedcolbert**
Implement viewer button in top left of scripture view. Needs style polish and proper labeling.

Implements #289

### CODE REVIEW

**Comment by chrisvire** [comment]
It shouldn't be over the scrollbar. So it needs some right padding.

image

**Comment by jakedcolbert** [comment]
see if you like it with a border

**Comment by chrisvire** [comment]
I don't see any change in the spacing. 

BTW, I see "Merge branch 'main'" in the list of commits?

**Review by chrisvire — APPROVED** [review]
👍

**Pull request merged**
